# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - macrodyne-it-functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'macrodyne-it-functions2'
  PACKAGE_PATH: 'requisition'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pushd ${{ env.PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: Create deployment zip
        run: |
          pushd ${{ env.PACKAGE_PATH }}
          zip -r ../deployment.zip . \
            --exclude "*.pyc" \
            --exclude "__pycache__/*" \
            --exclude ".git/*" \
            --exclude "local.settings.json"
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF543AB7848E40EA869D6AEEB6B383AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A43C0C109504E8A9F6058768EBCD910 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_470301F8FB4447BA9951B19923EAD208 }}

      - name: Deploy to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group rg-macrodyne-it-tools \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src deployment.zip
